#!/bin/bash
set -e


HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

WORK=$PWD

#config, build, and install latest UHD driver for USRP
function build_uhd {
        #install dependencies
	sudo dnf -y install boost-devel \
		python3-numpy \
		python3-mako \
		libusbx-devel

	mkdir -p $HERE/uhd && wget https://files.ettus.com/binaries/uhd/uhd_004.001.000.001-release/uhd_${UHD_VERSION}-release.tar.gz -P $HERE/uhd && \
	cd $HERE/uhd && tar xvzf uhd_${UHD_VERSION}-release.tar.gz && cd host && mkdir build && cd build && cmake ../ -DPYTHON_EXECUTABLE=/usr/bin/${PYTHON_VERSION}  -DRUNTIME_PYTHON_EXECUTABLE=/usr/bin/${PYTHON_VERSION} && \
	make -j4 && sudo make install && sudo ldconfig && sudo ${PYTHON_VERSION} /usr/local/lib64/uhd/utils/uhd_images_downloader.py 
}

function build_oai {
	#build OAI gNB
	cd $WORK
	git clone https://gitlab.eurecom.fr/oai/openairinterface5g $HERE/oai/  --branch ${OAI_VERSION} --recursive --depth 1 && \
	cp assets/patches/build_oai $HERE/oai/cmake_targets/build_oai && \
	cd $HERE/oai && /bin/sh oaienv && cd cmake_targets && \
	mkdir -p log && ./build_oai -I && ./build_oai --gNB -w USRP
}


function build_gnb {

	#build container image using RH ubi
	cd $WORK
	CONTAINER_ID=$(buildah from "$BASE_IMAGE")

	buildah run ${CONTAINER_ID} -- dnf -y install --enablerepo ${REPO} \
                                	boost \
                                	blas \
                                	atlas \
                                	lapack \
                                	libXpm \
                                	protobuf-c \
                                	libconfig \
                                	libusb \
                                	libusbx \
                                	libusbx-devel \
                                	lksctp-tools \
                                	iproute \
                                	iputils \
                                	udev \
                                	tcpdump 

	#add oai gNodeb libs
	buildah add ${CONTAINER_ID} ${HERE}/oai/cmake_targets/ran_build/build/nr-softmodem /oai/bin/
	buildah add ${CONTAINER_ID} ${HERE}/oai/targets/PROJECTS/GENERIC-NR-5GC/CONF/ /oai/etc/
	buildah add ${CONTAINER_ID} ${HERE}/oai/cmake_targets/ran_build/build/*.so /lib64/

	#copy udev rules
	buildah add ${CONTAINER_ID} /usr/local/lib64/uhd/utils/uhd-usrp.rules /etc/udev/rules.d/

	#add uhd bin and libs 
	
	buildah add ${CONTAINER_ID} /usr/local/bin/uhd_* /usr/local/bin
	buildah add ${CONTAINER_ID} /usr/local/share/uhd /usr/local/share/uhd
	buildah add ${CONTAINER_ID} /usr/local/lib64 /lib64

	buildah add ${CONTAINER_ID} /lib64/libforms.so.2 /lib64

	buildah run ${CONTAINER_ID} -- ln -sf /lib64/libuhd.so.4.1.0 /lib64/libuhd.so
	buildah run ${CONTAINER_ID} -- ln -sf /lib64/liboai_eth_transpro.so /lib64/liboai_transpro.so
	buildah run ${CONTAINER_ID} -- ln -sf /lib64/liboai_usrpdevif.so /lib64/liboai_device.so

	#add entrypoint
	buildah add ${CONTAINER_ID} $WORK/assets/scripts/entrypoint /bin/oai

	buildah config \
        	--entrypoint /bin/oai \
        	--workingdir /oai \
        	"$CONTAINER_ID" 

	buildah commit "$CONTAINER_ID" localhost/oai_gnb:latest
        
}


$HERE/build_uhd
$HERE/build_oai
$HERE/build_gnb
$HERE/load_image oai_gnb
