#!/bin/bash

set -e

dnf -y install gettext

GNB_IP=$(ip addr show eth0 | grep inet.*brd.*eth0 | awk '{print $2}') \
envsubst '$GNB_IP' < /oai/etc/${COMPONENT}.conf > /oai/etc/${COMPONENT}-prod.yaml

udevadm control --reload-rules && udevadm trigger

export UHD_IMAGES_DIR=/usr/local/share/uhd/images && uhd_usrp_probe

# https://gitlab.eurecom.fr/oai/openairinterface5g/-/commit/c9f72efc945fe75cf091b75e1e82b756d7bd3180
# execute the whole gnb stack in 5G-SA mode
/oai/bin/nr-softmodem -E --sa -O /oai/etc/${COMPONENT}-prod.conf